name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
  uuid: ^4.4.0
  # cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: 5.0.15
flutter:

  uses-material-design: true
